### ISSUE TITLE
chaining filters

### ISSUE THREAD

**Issue by aryszka** [zalando/skipper#56] opened 2015-11-18 14:15 UTC
allow this:

```
chainedFilter(p1, p2): filter1("value", p1) -> filter2(1, p2, 2, 3);
noopFilter():;
route1: noopFilter() -> chainedFilter("param1", 1.5) -> otherFilter() -> ":8080"
```

involves:
- eskip syntax
- runtime route table construction
- etcd: (with prefix /filters on the same level as /routes)
- innkeeper
- eskip tool

**Comment by LappleApple** [comment] 2016-08-09 10:18
If "Help Wanted" can also apply, thumbs-up this comment.

**Comment by lmineiro** [comment] 2016-08-09 21:21
This is kind of a duplicate of https://github.com/zalando/skipper/issues/182

**Closed by lmineiro** 2016-08-09 21:21 UTC
Labels: enhancement
