### ISSUE TITLE
Make multi-arch images publicly available

### ISSUE THREAD

**Issue by spr-mweber3** [zalando/skipper#2114] opened 2022-10-26 15:23 UTC
Hey there, I'd like to know why the multi-arch images that you build are not made publicly available? We'd like to utilize them in our mixed amd64/arm64 setup without having to worry what image with which tag gets deployed where.

Is there any specific reason why you're not storing the multi-arch images in the same registry as your other images?

**Comment by szuecs** [comment] 2022-10-26 17:10
@spr-mweber3 the problem is that our opensource registry does not support multi-arch containers

**Comment by spr-mweber3** [comment] 2022-10-26 17:17
GitHub Container Registry (ghcr.io) [supports multi-arch images](https://github.blog/changelog/2020-09-17-github-container-registry-support-for-multi-arch-images/) for almost two years now. Maybe this could be an option for you? I think it makes perfectly sense since you're hosting the code here already, too.

It's pretty straight-forward to set-up.

**Comment by szuecs** [comment] 2022-10-27 12:05
I don't see there the docs for setting it up. Maybe you want to create a PR for this?

**Comment by MustafaSaber** [comment] 2022-10-31 15:12
Hi @spr-mweber3 , I'm giving it a try let's see how it will go. We don't mind creating Github workflow for it. so feel free to edit on the mentioned PR.

**Comment by spr-mweber3** [comment] 2022-10-31 16:55
Thanks for trying to progress on the matter. I'm not sure if having a separate flow in addition to your central delivery makes a whole lot of sense. I think it's easier integrated there. Nevertheless, I'll see to provide a PR with a GitHub Workflow that we use ourselves.

**Comment by MustafaSaber** [comment] 2022-11-03 10:46
Hi @spr-mweber3 can you test the current public images in your setup?

```
docker pull ghcr.io/zalando/skipper:v0.14.2
docker pull ghcr.io/zalando/skipper-arm64:v0.14.2
docker pull ghcr.io/zalando/skipper-armv7:v0.14.2
```

**Comment by spr-mweber3** [comment] 2022-11-03 12:35
With `docker manifest inspect --verbose ghcr.io/zalando/skipper:v0.14.2` I can see that I can pull the image but it's not multi-arch. It's `amd64` only. But I guess you're doing one step after another here.

**Comment by spr-mweber3** [comment] 2022-11-04 15:07
Awesome work, thank you @MustafaSaber ... really appreciate it.

**Comment by MustafaSaber** [comment] 2022-11-07 10:14
urw! It's merged now with the right tag  🥳

**Comment by MustafaSaber** [comment] 2023-01-02 09:56
Closed with #2173

**Closed by MustafaSaber** 2023-01-02 09:56 UTC
