### ISSUE TITLE
Support for "slow start mode"

### ISSUE THREAD

**Issue by mikkeloscar** [zalando/skipper#1249] opened 2019-11-25 13:58 UTC
**Is your feature request related to a problem? Please describe.**
Some backends (e.g. JVM based) benefits from a warm-up period where they don't get the full traffic load but instead slowly get more and more of the traffic load in order to warm-up.

AWS Application Load Balancers has a solution for this in the form of "slow start mode": https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-target-groups.html#slow-start-mode

**Describe the solution you would like**
Could be beneficial if skipper supported something similar to a "slow start mode" where you could configure how long it should take before an endpoint in a `roundRobin` backend is getting the full amount of traffic.

**Describe alternatives you've considered (optional)**
The alternative would be for applications to implement some sort of synthetic load which could warm up a pod before it's returning ready on the readinessProbe.

**Additional context (optional)**
@aryszka pointed out that the tricky part about this could be to keep state between route updates

**Would you like to work on it?**
Sure

**Comment by szuecs** [comment] 2019-11-26 13:41
Please make sure it's not only based on the LB Algorithm. Basically I think you need to have a by chance filter on the memberlist before applying the algorithm.
You would need to subset `ctx.Route.LBEndpoints` for example in:
https://github.com/zalando/skipper/blob/master/loadbalancer/algorithm.go#L53

And keep state for a certain amount of time to do the slow fade-in

**Comment by mikkeloscar** [comment] 2019-11-26 13:46
@szuecs thanks for the feedback. jFYI: Currently I will not attempt any implementation on this. It was just to start the discussion.

**Comment by szuecs** [comment] 2019-12-09 14:20
In general this should not be kubernetes specific. I put it into enhancement

**Comment by otrosien** [comment] 2019-12-09 17:38
Isn't this a duplicate of https://github.com/zalando/skipper/issues/1207 ?

**Comment by szuecs** [comment] 2019-12-09 18:55
True

**Closed by szuecs** 2019-12-09 18:55 UTC
Labels: enhancement
