### ISSUE TITLE
Skipper HTTP->HTTPS 308 redirect causes Android app crashes

### ISSUE THREAD

**Issue by roffe** [zalando/skipper#796] opened 2018-09-18 19:20 UTC
There is something in some Android devices that causes apps to crash when they hit a endpoint where the HTTP redirect is done with a 308

After basicly reverting https://github.com/zalando/skipper/commit/71b6452a65d87c67d8c8f89b708e4f4f50f362dd the app on multiple devices no longer crashes.

**Comment by ruiaraujo** [comment] 2018-09-18 19:47
@roffe which application?

**Comment by szuecs** [comment] 2018-09-18 20:34
Someone told me a version of internet explorer can’t deal with 308, too.
But the one also told that a cdn provider (Cloudflare?) also use 308. Maybe we should have an option to set 301 instead.

@roffe do you want to change it with a flag to skipper or in an ingress annotation?

**Comment by szuecs** [comment] 2018-09-18 20:36
I think it’s a duplicate of https://github.com/zalando/skipper/issues/794

**Closed by szuecs** 2018-09-18 20:36 UTC
