### ISSUE TITLE
Flaky TestTeeEndToEndBody2TeeRoutesAndClosing

### ISSUE THREAD

**Issue by szuecs** [zalando/skipper#2643] opened 2023-10-04 08:27 UTC
```
--- FAIL: TestTeeEndToEndBody2TeeRoutesAndClosing (0.01s)
    tee_test.go:268: shadow handler got a request, but should not
panic: close of closed channel [recovered]
	panic: close of closed channel

goroutine 52 [running]:
testing.tRunner.func1.2({0x182fd00, 0x1aeb550})
	/opt/hostedtoolcache/go/1.21.1/x64/src/testing/testing.go:1545 +0x366
testing.tRunner.func1()
	/opt/hostedtoolcache/go/1.21.1/x64/src/testing/testing.go:1548 +0x630
panic({0x182fd00?, 0x1aeb550?})
	/opt/hostedtoolcache/go/1.21.1/x64/src/runtime/panic.go:920 +0x270
runtime.Goexit()
	/opt/hostedtoolcache/go/1.21.1/x64/src/runtime/panic.go:541 +0x188
testing.(*common).FailNow(0xc000308b60)
	/opt/hostedtoolcache/go/1.21.1/x64/src/testing/testing.go:999 +0x85
testing.(*common).Fatal(0xc000308b60, {0xc0001cdaa8, 0x1, 0x1})
	/opt/hostedtoolcache/go/1.21.1/x64/src/testing/testing.go:1076 +0x88
github.com/zalando/skipper/filters/tee.TestTeeEndToEndBody2TeeRoutesAndClosing(0xc000308b60)
	/home/runner/work/skipper/skipper/filters/tee/tee_test.go:268 +0x158a
testing.tRunner(0xc000308b60, 0x19bb728)
	/opt/hostedtoolcache/go/1.21.1/x64/src/testing/testing.go:1595 +0x239
created by testing.(*T).Run in goroutine 1
	/opt/hostedtoolcache/go/1.21.1/x64/src/testing/testing.go:1648 +0x82b
FAIL	github.com/zalando/skipper/filters/tee	0.037s
```

**Comment by AlexanderYastrebov** [comment] 2023-10-04 08:58
duplicate of https://github.com/zalando/skipper/issues/2435

**Closed by AlexanderYastrebov** 2023-10-04 08:58 UTC
Labels: flakytest
