### ISSUE TITLE
Surprising route behaviour with more specific sub-path routes

### ISSUE THREAD

**Issue by mo-gr** [zalando/skipper#116] opened 2016-03-03 15:41 UTC
If I have the following three routes:

`a: Path("/foo/*_") -> "https://foo.org"`
`b: Path("/foo/bar") && Traffic(0.5, "bar", "foobar") -> "https://bar.org"`
`z: * -> "https://catch.all"`

I would expect a request with the path `/foo/bar` to hit `foo.org` in half the time and `bar.org` the other half. However, all the requests, that don't hit `bar.org` end up being route to `catch.all`.

This is probably due to the way, the path-match tree is constructed, but it is very surprising and dangerous behaviour.

**Comment by aryszka** [comment] 2016-03-03 15:46
this may need to be handled in github.com/zalando/pathmux

**Comment by aryszka** [comment] 2016-03-03 16:06
the right thing to do would be to move the non-path type predicate matching into the tree lookup in pathmux, so that this would be solved by the backtracking in pathmux

**Comment by ewgRa** [comment] 2016-03-20 23:13
Is Traffic predicate in open-source?

"[APP]ERRO[0000] predicate not found: 'Traffic'"

Can anybody share it?

**Comment by ewgRa** [comment] 2016-03-21 00:08
I think tests from #130 is a right reproduce of this bug.

**Comment by ewgRa** [comment] 2016-03-21 09:13
@aryszka instead of move predicates to pathmux (that seems not so good from architecture perspective, since pathmux work only with path) how about this two options?

1. Add to patchmux - "skipStatic" option, or something like this. When skipper get from pathmux static route and predicates do not match it - skipper can ask pathmux to look another route in non-static routes. There is no performance overhead.

2. Add to patchmux - "continueFrom" option. I don't look deeply to pathmux algorithm, but I think it is possible. When skipper get from pathmux static route and predicates do not match it - skipper can ask pathmux to look routes and start searching from route that skipper get first time. I think there is no big performance overhead.


How this sounds for you?

**Comment by aryszka** [comment] 2016-03-30 15:05
@ewgRa 
I agree that we shouldn't move any skipper specific logic or types to pathmux. For the solution however, I am thinking now in something else. The values stored in pathmux leaves are currently of type `interface{}`. This could replaced with something like:

```
type Value interface {
    Match(*http.Request) bool
}
```

...and when pathmux finds a leaf that matches this way, would ask the implementation if it really wants to match for the given request, and consider it matching only if returns true, otherwise it would continue with backtracking.

This should yet verified in pathmux if it is possible.

**Comment by ewgRa** [comment] 2016-03-30 16:19
Kind of "match callback" way.

Is it critical bug for you?

I will take it, but don't know when I can finish it. Maybe week, maybe even more. So, if it is critical - feel free to work on fix yourself.

**Comment by aryszka** [comment] 2016-03-30 17:28
yeah, just like a callback.

currently, it is not critical, but we'll need some fix for this in a matter of a few weeks, as more people will be involved in defining routes. if you like this bug, then just pls feel free to go after it.

if the fix becomes critical, then we can still join our efforts, i guess..

some notes on working with https://github.com/zalando/pathmux:

1. it would be nice, if the current tree.Add method would still accept any interface{} like now, and it would behave as if the above mentioned Value.Match would return always true. There could be a new method, tree.AddMatcher(Value), that would behave in the "callback" way. (With a wrapper structure, tree.Add could call into tree.AddMatcher.)

This way the pathmux lib would stay backwards compatible, and in skipper we would only need to replace the calls to tree.Add. I know that we could type switch inside the tree.Add method, too, but I prefer to have this behavior explicitly described by the package signature.

2. it would be nice to run the benchmarks of pathmux on master and on the work branch time-to-time to get a comparison between the before and after state, to avoid surprisingly big degradation.

**Comment by ewgRa** [comment] 2016-03-31 10:13
ok, I will take it. If it become critical for you - feel free to fix it yourself.

**Comment by ewgRa** [comment] 2016-04-01 22:49
> Match(*http.Request) bool

pathmux don't know anything about request, and also from architecture perspective share request to pathmux not a right idea.

For now I implement it as "isMatch() bool", but don't find good solution how to use it in skipper, since request we know only at Matcher.match that call Tree.Lookup. For now I see only option to change Lookup signature, or add also LookupWithMatcher that will have request inside and isMatch(leafNode...) or something like this.

Another option make "Match({}interface)" bool and send request as interface to pathmux.

Will think on it. Maybe you have idea? Maybe do this as true "callback(leafValue) bool" somehow?

Also I see some improvements on pathmux, as from performance perspective, as from better code understanding. But this can be done after fix this bug to avoid conflicts.

**Comment by ewgRa** [comment] 2016-04-02 10:47
> "callback(leafValue) bool"

https://github.com/zalando/pathmux/pull/2 - have performance degradation, but will work.

I have also idea that channels here can help to implement "found->check->continue" way, but don't sure on 100%.

**Comment by ewgRa** [comment] 2016-04-02 11:56
Fix for this bug https://github.com/zalando/skipper/pull/133, with usage of https://github.com/zalando/pathmux/pull/2 implementation

**Closed** 2016-04-21 14:30 UTC
Labels: bug
